name: Release

on:
  release:
    types:
      - published

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Update manifest version
        run: python3 .github/scripts/update_manifest_version.py --version ${{ github.event.release.tag_name }}

      - name: Create zip
        run: |
          cd custom_components/aptus
          zip aptus.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/aptus/aptus.zip
          asset_name: aptus.zip
          tag: ${{ github.ref }}
          overwrite: true
